spring.application.name=auth
server.port=8083
server.servlet.context-path=/auth-ms

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# JWT
jwt.secret=B8/aV2WyX9TCH+r0hLSOdZl4f5k6bEwnxJ3qM/o2u+A3cR9gHlV7yK0pLwU8iZ/jI+eS6wY5nB7tD/fRz8kE/g==
jwt.expiration=86400000